# Generated by Django 5.2.11 on 2026-02-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="idempotencyrecord",
            new_name="core_idempo_user_id_ebc4c0_idx",
            old_name="core_idempo_user_cr_7bfeae_idx",
        ),
        migrations.RenameIndex(
            model_name="idempotencyrecord",
            new_name="core_idempo_key_b2286d_idx",
            old_name="core_idempo_key_0d2b10_idx",
        ),
    ]
