# Generated by Django 5.2.12 on 2026-03-04 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0002_rename_core_idempo_user_cr_7bfeae_idx_core_idempo_user_id_ebc4c0_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminOperationalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.CharField(max_length=255)),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("INTEGER", "Integer"),
                            ("FLOAT", "Float"),
                            ("BOOLEAN", "Boolean"),
                            ("STRING", "String"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_operational_settings_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("USER_ROLE_UPDATED", "User role updated"),
                            ("USER_ACCESS_UPDATED", "User access updated"),
                            ("CONFIG_UPDATED", "Configuration updated"),
                            ("HEALTH_CHECKED", "Health checked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("setting_key", models.CharField(blank=True, default="", max_length=64)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_target_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="core_admina_event_t_f74394_idx"
                    ),
                    models.Index(
                        fields=["actor", "created_at"], name="core_admina_actor_i_ffc3f5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("status", models.CharField(max_length=16)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_health_checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "checked_at"], name="core_adminh_status_a7290e_idx"
                    )
                ],
            },
        ),
    ]
