# path: policylens/apps/claims/management/commands/generate_synthetic_ml_data.py
"""
Generate deterministic synthetic training data for the completeness classifier.

This creates a CSV with:
- FEATURE_NAMES columns
- is_incomplete label

Synthetic labels are generated by a rule plus limited noise to produce learnable patterns.
"""

from __future__ import annotations

import csv
import random
from pathlib import Path

from django.core.management.base import BaseCommand

from policylens.apps.claims.ml.contracts import FEATURE_NAMES


class Command(BaseCommand):
    """Generate synthetic ML dataset CSV."""

    help = "Generate deterministic synthetic training data for completeness classifier."

    def add_arguments(self, parser) -> None:
        parser.add_argument(
            "--out", required=True, help="Output CSV path, e.g. artifacts/ml/data/synthetic.csv"
        )
        parser.add_argument("--rows", type=int, default=2000, help="Number of rows to generate.")
        parser.add_argument("--seed", type=int, default=42, help="Deterministic RNG seed.")

    def handle(self, *args, **options) -> None:
        out = Path(options["out"])
        out.parent.mkdir(parents=True, exist_ok=True)

        rows = int(options["rows"])
        seed = int(options["seed"])
        rng = random.Random(seed)

        fieldnames = list(FEATURE_NAMES) + ["is_incomplete"]

        with out.open("w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()

            for _ in range(rows):
                # Core categorical one-hot signals.
                claim_type_is_claim = rng.choice([0, 1])
                claim_type_is_policy_change = 1 - claim_type_is_claim

                priority_bucket = rng.choices(["high", "normal", "low"], weights=[2, 5, 3])[0]
                priority_is_high = 1 if priority_bucket == "high" else 0
                priority_is_normal = 1 if priority_bucket == "normal" else 0
                priority_is_low = 1 if priority_bucket == "low" else 0

                # Text proxy features.
                summary_length = rng.randint(0, 300)
                summary_has_digits = 1 if rng.random() < 0.25 else 0

                # Document features.
                documents_count = rng.choices([0, 1, 2, 3], weights=[3, 5, 3, 1])[0]
                documents_total_bytes = 0
                documents_has_pdf = 0
                documents_has_image = 0
                documents_has_text = 0

                if documents_count > 0:
                    documents_total_bytes = rng.randint(5_000, 2_000_000) * documents_count
                    documents_has_pdf = 1 if rng.random() < 0.55 else 0
                    documents_has_image = 1 if rng.random() < 0.35 else 0
                    documents_has_text = 1 if rng.random() < 0.20 else 0
                    # Ensure at least one type is present sometimes.
                    if documents_has_pdf + documents_has_image + documents_has_text == 0:
                        documents_has_pdf = 1

                # Checklist features.
                checklist_required_count = rng.choices([0, 2, 3, 4], weights=[1, 4, 3, 2])[0]
                checklist_satisfied_count = 0
                checklist_missing_required_count = 0
                if checklist_required_count > 0:
                    checklist_satisfied_count = rng.randint(0, checklist_required_count)
                    checklist_missing_required_count = (
                        checklist_required_count - checklist_satisfied_count
                    )

                # Rule-based label with small noise.
                incomplete = 0
                if documents_count == 0:
                    incomplete = 1
                if summary_length < 40:
                    incomplete = 1
                if checklist_missing_required_count > 0:
                    incomplete = 1

                # Noise: flip a small proportion for learnable but imperfect data.
                if rng.random() < 0.05:
                    incomplete = 1 - incomplete

                record = {
                    "claim_type_is_claim": float(claim_type_is_claim),
                    "claim_type_is_policy_change": float(claim_type_is_policy_change),
                    "priority_is_high": float(priority_is_high),
                    "priority_is_normal": float(priority_is_normal),
                    "priority_is_low": float(priority_is_low),
                    "summary_length": float(summary_length),
                    "summary_has_digits": float(summary_has_digits),
                    "documents_count": float(documents_count),
                    "documents_total_bytes": float(documents_total_bytes),
                    "documents_has_pdf": float(documents_has_pdf),
                    "documents_has_image": float(documents_has_image),
                    "documents_has_text": float(documents_has_text),
                    "checklist_required_count": float(checklist_required_count),
                    "checklist_satisfied_count": float(checklist_satisfied_count),
                    "checklist_missing_required_count": float(checklist_missing_required_count),
                    "is_incomplete": int(incomplete),
                }

                writer.writerow(record)

        self.stdout.write(self.style.SUCCESS(f"Wrote {rows} rows to {out}"))
