# Generated by Django 5.2.10 on 2026-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["claim", "created_at"],
                name="claims_audi_claim_i_39c7e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_type"],
                name="claims_audi_event_t_c60ff3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="checklistitem",
            index=models.Index(
                fields=["claim", "is_satisfied"],
                name="claims_chec_claim_i_fc4ace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["status", "priority"],
                name="claims_clai_status_3ce1a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["created_at"],
                name="claims_clai_created_d933ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="claimdocument",
            index=models.Index(
                fields=["claim", "uploaded_at"],
                name="claims_clai_claim_i_84fe32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["policy_number"],
                name="claims_poli_policy__d91f52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policy",
            index=models.Index(
                fields=["status"],
                name="claims_poli_status_356882_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="policyholder",
            index=models.Index(
                fields=["email"],
                name="claims_poli_email_f73d01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewdecision",
            index=models.Index(
                fields=["claim", "decided_at"],
                name="claims_revi_claim_i_ce456f_idx",
            ),
        ),
    ]
