# Generated by Django 5.2.10 on 2026-01-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_auditevent_claims_audi_claim_i_39c7e4_idx_and_more"),
        ("claims", "0002_documents_and_notes"),
    ]

    operations = []
