# Generated by Django 5.2.10 on 2026-01-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("claims", "0003_merge_20260126_1723"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="internalnote",
            index=models.Index(
                fields=["claim", "created_at"],
                name="claims_inte_claim_i_2f3072_idx",
            ),
        ),
    ]
