# Generated by Django 5.2.10 on 2026-02-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_mlscore_metadata_fields"),
        ("claims", "0004_internalnote_claims_inte_claim_i_2f3072_idx"),
    ]

    operations = []
